
#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
#include "TH2.h"
#include "TRandom.h"


void expo_pr()
{
   //read the Tree generated by tree1w and fill two histograms


   if (remove ("test.root") !=0 || remove ("angXout.txt") != 0 || remove ("angYout.txt") != 0 || remove ("energy.txt") != 0) 
	perror ("Error deleting file" );
   else 
	puts (" File succesfully deleted ");

   //note that we use "new" to create the TFile and TTree objects !
   //because we want to keep these objects alive when we leave this function.
   TFile *f1 = new TFile("proton_si001ax_100K_DEB_10um.root");
   TFile *f2 = new TFile("test.root","NEW");
   TTree *t1 = (TTree*)f1->Get("sim");
   TTree *t2 = new TTree("tree", "simple tree");

   TLeaf *angX = t1->GetLeaf("angXout");
   TLeaf *angY = t1->GetLeaf("angYout");
   TLeaf *ene  = t1->GetLeaf("energy,MeV");

   Double_t angXout;
   TH1F *hpx   = new TH1F("hpx","angXout",1000,-17,17);
   TH1F *hpy   = new TH1F("hpy","angYout",1000,-17,17);
   TH1F *hene   = new TH1F("hene","energy",100,0,1);
   t2->Branch("hpx","TH1F",&hpx);
   t2->Branch("hpy","TH1F",&hpy);
   t2->Branch("hene", "TH1F", &hene);

   //create two histograms

   //read all entries and fill the histograms
   Long64_t nentries = t1->GetEntries();
   cout << " number of entries " << nentries << endl;
   for (Long64_t i=0;i<nentries;i++) {
     //leaf->GetEntry(i);
     angX->GetBranch()->GetEntry(i);
     angY->GetBranch()->GetEntry(i);
     ene->GetBranch()->GetEntry(i);
     hpx->Fill(angX->GetValue());
     hpy->Fill(angY->GetValue());
     hene->Fill(ene->GetValue());
  }
  hpx->Write();
  hpy->Write();
  hene->Write();
  //t2->Write();

  //hpx->Draw(); // nupiesia histo gerai.


  ofstream myfile;
  Int_t n=hpx->GetNbinsX();
  Int_t m=hpy->GetNbinsX();
  Int_t p=hene->GetNbinsX();


  myfile.open ("angXout.txt");
	
     for (Int_t i=1; i<=n; i++) {
      myfile << (hpx->GetBinLowEdge(i)+hpx->GetBinWidth(i)/2) << "\t" << hpx->GetBinContent(i) << "\n";
	}
   myfile.close();

   myfile.open("angYout.txt");
     for (Int_t i=1; i<=m; i++) {
      myfile << (hpy->GetBinLowEdge(i)+hpy->GetBinWidth(i)/2) << "\t" << hpy->GetBinContent(i) << "\n";
	}
   myfile.close();

   myfile.open("energy.txt");
     for (Int_t i=1; i<=p; i++) {
      myfile << (hene->GetBinLowEdge(i)+hene->GetBinWidth(i)/2) << "\t" << hene->GetBinContent(i) << "\n";
	}
   myfile.close();

  if (gROOT->IsBatch()) return;
  new TBrowser();
}
